FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build
WORKDIR ClientStarwar/StarWar.Client/
COPY . .
RUN dotnet build
RUN dotnet publish --configuration Release -o out PizzaBox.Client/PizzaBox.Client.csproj

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR dist/
COPY --from=build ClientStarWar/StarWar.Client/out/ ./
CMD ["dotnet", "PizzaBox.Client.dll"]